---
site_name: "JumpStart Docs"
site_description: "Documentation for CSH Jumpstart System"
theme: 
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tops
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.shareable
    - navigation.search.suggest
    - navigation.search.suggest.indexes
    - navigation.search.suggest.terms
    - navigation.search.suggest.results
    - navigation.search.suggest.results.indexes
  logo: images/jumpstart_half.png
  favicon: images/jumpstart_small.png

use_directory_urls: false

nav:
  - Home: index.md
  - Getting Started:
  - Endpoints:
      - v1: endpoints/v1.md
  - Scripts:
      - Setup: 

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [""]
          options:
            heading_level